taco:
  orders:
    pageSize: 10

    discount:
      codes:
        abcdef: 10

---

spring:
  datasouce:
    url: jdbc:mysql://localhost:3306/taco
    username: root
    password: 327265266425262
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        generate_statictic: true
        ddl-auto: validate
  config:
    activate:
      on-profile: prod

logging:
  level:
    taco: WARN